#!/usr/bin/with-contenv bash

echo "Starting Sia Server."

exec \
  socat tcp-listen:9980,reuseaddr,fork tcp:localhost:8000 & \
    $SIA_DIR/siad \
      --modules "$SIA_MODULES" \
      --sia-directory "$SIA_DATA_DIR" \
      --api-addr "localhost:8000"
