#!/usr/bin/with-contenv bash

cleanup() {
  rm -rf /tmp/Sia*
}

check_latest() {
  RESULT="$(python3 /app/update.py --check)"
  [[ $? -ne 0 ]] && download_failed
}

download_dry_run() {
  RESULT="$(python3 /app/update.py --dry-run -v $SIA_VERSION -o /tmp)"
  [[ $? -ne 0 ]] && download_failed
}

download() {
  RESULT="$(python3 /app/update.py -v $SIA_VERSION -o /tmp)"
  [[ $? -ne 0 ]] && download_failed
}

update_not_required() {
  echo "Update not required. Current version and desired version match."
  exit 0
}

download_failed() {
  echo "Download failed. Terminating update script."
  exit 1
}

update_failed() {
  echo "Update failed. Terminating update script."
  exit 1
}

if [[ -f "${SIA_DIR}/siad" ]]; then
  echo "siad found. Checking versions."
  RESULT="$(${SIA_DIR}/siad version)"
  [[ "$RESULT" =~ ^.*(v[0-9]+\.[0-9]+\.[0-9]+).*$ ]] && CUR_VERSION="${BASH_REMATCH[1]}"
  if [[ "${SIA_VERSION,,}" = "latest" ]] || [[ ! -n $SIA_VERSION ]]; then
    LATEST="$RESULT"
    echo "Current version is $CUR_VERSION. Latest version is $RESULT."
    [[ "$LATEST" = "$CUR_VERSION" ]] && update_not_required
  else
    echo "Current version is $CUR_VERSION. Desired version is $SIA_VERSION."
    [[ "$SIA_VERSION" = "$CUR_VERSION" ]] && update_not_required
  fi
fi

download
[[ $RESULT =~ ^.*-(v[0-9]+\.[0-9]+\.[0-9]+)-.*$ ]] && DOWNLOAD_VERSION="${BASH_REMATCH[1]}"
echo "Downloaded version $DOWNLOAD_VERSION."

if [[ $RESULT =~ ^.*\/([0-9a-zA-Z\.\-]+)\.zip$ ]] && [[ -f "${BASH_REMATCH[0]}" ]]; then
  unzip -o -j "${BASH_REMATCH[0]}" "${BASH_REMATCH[1]}/siac" -d "${SIA_DIR}"
  [[ $? -ne 0 ]] && update_failed
  unzip -o -j "${BASH_REMATCH[0]}" "${BASH_REMATCH[1]}/siad" -d "${SIA_DIR}"
  [[ $? -ne 0 ]] && update_failed
  cleanup
fi

if [[ -f "$SIA_DIR/siac" ]] && [[ -f "$SIA_DIR/siad" ]]; then
  echo "Update completed successfully."
  cleanup
  exit 0
else
  update_failed
fi
